<?php

use Illuminate\Database\Seeder;
use TestKit\App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array('id' => '1','name' => 'Liver Disease Test','caption_text' => 'Did you know that the only organ in the body that can regenerate is the liver?
            Liver the largest solid organ of the body sits just under the rib cage on the right side of the abdomen.
            The liver is associated with various functions of the body as:
            Synthesis  of Cholesterol
            Production of Hormones and Enzymes
            Deactivation of Toxic / Poison
            Stores of Vitamins
            Production of Bile
            Warehouse of Glucose

            ', 'description' => 'Some of the Symptoms of Liver Disease







            Jaundice
            Dark Urine
            Loss of appetite
            Imbalance in weight
            Itchy skin
            Abdominal Pain











            Vomiting
            Pale stool colour
            Diarrhea






            Are you at risk?






            Alcohol consumption
            Exposure to chemicals or toxins
            Obesity
            Diabetes
            Blood borne pathogens (Hepatitis C )


            Some of the diagnosis biomarkers tested in our lab
            How is Liver Disease Diagnosed?
            To detect monitor and evaluate the liver disease or damage a group of tests is performed. The panel usually consists of group of tests that are run on blood sample. They include:
            Alanine Aminotransferase (ALT)
            A liver enzyme that is also present in the heart, kidneys and skeletal muscle to lesser level. Its measurement aids in detection of liver and biliary disorders in the clinic.
            Aspartate aminotransferase (AST)
            The heart, liver, and muscles all produce this enzyme. Because AST readings arent as specific for liver damage as ALT, theyre often used with ALT to rule out liver disease. AST is released into the circulation when the liver is injured. An elevated AST level might point to a liver or muscle issue.
            Alkaline phosphatase (ALP)
            An enzyme generated by the bile ducts, but also by the bones, intestines, and the placenta during pregnancy (afterbirth). ALP readings over a certain threshold can suggest liver inflammation, bile duct obstruction, or bone disease.
            Gamma Glutamyl Transpeptidase (GGTP)
            The liver has the largest amounts of this enzyme, which is present in numerous organs throughout the body. GGT levels in the blood are raised in most disorders that affect the liver or bile ducts.
            Bilirubin , Direct
            It measures the morphology of bilirubin that is conjugated (bound to another compound) in the liver. It increases only in liver disease.

            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '40.00'),
            array('id' => '3','name' => 'Pancreas Disease Test','caption_text' => 'Pancreatitis is inflammation of pancreas. Pancreas is a large gland behind the stomach and has two main functions – to make insulin and to make digestive juices or enzymes. Pancreatitis is the result of enzymes damage the pancreas which causes inflammation.
            Symptoms
            Dehydration
            Loss of appetite






            Diarrhoea
            Indigestion
            High Temperature
            Jaundice
            Vomiting
            Fast Heartbeat
            Swelling of tummy
            Dehydration
            Loss of Appetite
            ', 'description' => 'Are you at risk ?







            Diabetes
            Gall Stone
            High Triglycerides
            Obesity
            Smoking
            Alchol user
            Genetic disorder of Pancreas

            Diagnosis biomarker tested in our lab
            Amylase and Lipase test
            Pancreatitis is diagnosed with amylase and lipase testing. The tests determine how much of these enzymes are circulating in your blood.
            ', 'status' => '1', 'price' => '40.00'),
            array('id' => '5','name' => 'Kidney Disease Test','caption_text' => 'The kidneys are vital organs that functions to clean our blood. Kidney disease indicates that kidneys are damaged and can’t filter blood by extracting extra water and wastes out of your blood. Various medical conditions can cause the kidneys to stop working properly for a short time – for example, if blood isn’t pumped around the body properly or if an enlarged prostate or kidney stones make urine build up in the kidneys.
            The kidney is associated with various functions of the body as:
            Creating hormones to aid RBC production
            Promote bone health
             Body homeostasis
            Regulation of blood osmolarit
            Fluid Balance
            ', 'description' => 'Some of the Symptoms of Kidney Disease







            weight loss and poor appetite
            swollen ankles, feet or hands
            shortness of breath
            Blood in Urine
            Itchy skin
            muscle cramps


            Are you at risk?







            Smoking
            Acute kidney injury
            Obesity
            Diabetes
            Genetic component
            Hypertension


            Diagnosis biomarker tested in our lab
            To detect monitor and evaluate the kidney disease or damage a group of tests is performed. The panel usually consists of group of tests that are run on blood sample. They include:
            Albumin (BCG)
            This test measures the amount of the protein albumin in your blood. This test can help diagnose, evaluate, and watch kidney and liver conditions. When your kidneys start to fail, albumin starts to leak into your urine. This causes a low albumin level in your blood.
            Creatinine Enzymatic
            Kidney infections and bladder problems can raise creatinine levels. Anything that impairs kidney function can raise blood creatinine levels. This test shows how much creatinine has passed through your kidneys into your urine. It helps show how well your kidneys are removing the waste products from your blood.
            Phosphorus
            The kidneys filter and remove excess phosphate from the blood. If phosphate levels in your blood are too high or too low, it can be a sign of kidney disease or other serious disorder. High phosphorus levels can cause damage to your body. Extra phosphorus causes body changes that pull calcium out of your bones, making them weak.
            Total Protein Plus
            A total protein test measures the combined amount of both albumin and globulin. Low total protein levels can indicate kidney or liver disease while high total protein may be indicative of dehydration.
            Urea
            The blood urea nitrogen test, which is also called a BUN or serum BUN test, measures how much of the waste product you have in your blood.
            Uric Acid
            Measurement of uric acid in urine is used to help diagnose the cause of recurrent kidney stone formation
            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '50.00'),
            array('id' => '6','name' => 'Electrolytes panel Test','caption_text' => 'An electrolyte panel is a blood test to measures the level of seven electrolytes in the blood. Certain conditions, including dehydration, cardiovascular disease and kidney disease, can cause electrolyte levels to become too high or low
            Electrolytes play a critical role in:
            Balancing fluids in your body.
            Controlling your heart rate and rhythm.
            Promoting bone and dental health.
            Supporting nerve and muscle function.
            Stabilizing blood pressure.
            Symptoms
            Swelling from excessive accumulation of watery fluid (Edema)
            Nausea
            Weakness
            Confusion
            Dizziness
            Cramps
            Irregular heartbeat
            ', 'description' => 'Diagnosis of biomarker in our lab
            An electrolyte panel measures the concentrations of a variety of minerals in your blood, including:
            Sodium helps neuron and muscle function by controlling fluid levels.
            Potassium aids in the operation of the heart, nerves, and muscles, as well as metabolism.
            Calcium is important for your musculoskeletal (bones and muscles), neurological, and circulatory systems.
            Chloride Aids in the maintenance of normal blood pressure and body fluid levels.
            Magnesium Helps nerve and muscle function as well as bone and tooth formation (skeletal system).
            Phosphate Supports nerve and muscle function as well as the development of healthy teeth and bones.
            Bicarbonate Keeps the equilibrium of acids and basic alkaline chemicals in the blood healthy (acid-base balance). It also transports carbon dioxide throughout the body.

            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '40.00'),
            array('id' => '7','name' => 'Anaemia Test','caption_text' => 'Anaemia is a disorder in which your bodys tissues dont get enough oxygen because you dont have enough healthy red blood cells. Anaemia, commonly known as low haemoglobin, can leave you feeling exhausted and weak.
            Symptoms
            Anaemia symptoms vary according to its severity. Common symptoms include






            Weakness and Fatigue
            Pale or yellowish skin
            shortness of breath
            Irregular heartbeat
            Chest pain
            Dizziness
            Headaches
            Cold hands and Feet
            Pale skin
            ', 'description' => 'Are you at risk ?
            Age
            Menopause
            Pregnancy
            Intestinal Disorder
            Genetic or family history
            Diet lacking Vitamins and minerals

            Diagnosis
            Ferritin test: A ferritin test determines how much ferritin is in your blood. Ferritin is an iron-containing blood protein. A ferritin test tells your doctor how much iron is stored in your body.If a ferritin test reveals a lower-than-normal ferritin level in your blood, it means your bodys iron reserves are low and you have iron deficiency.
            Transferrin test: Transferrin is a direct measure of the iron binding capacity. Transferrin is thus useful in assessing iron balance.
            Iron Test
            STRF

            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '40.00'),
            array('id' => '8','name' => 'Rheumatoid Test','caption_text' => 'Rheumatoid arthritis is a long-term inflammatory condition that affects more than your joints. The illness can harm a range of body systems in certain people, including the skin, eyes, lungs, heart, and blood vessels. Rheumatoid arthritis is an autoimmune disease in which your immune system assaults your own bodys tissues.
            Symptoms
            Weakness and Fatigue
            Morning Stifness
            Joint Pain
            Joint Swelling
            Fever
            Numbness or Tingling
            Decrease in range of motion
            ', 'description' => 'Are you at risk?

            Family History
            Gender
            Obesity
            Viral Infection
            Injury to Bone


            Diagnosis
            Rheumatoid factor test: The RF test detects the presence of Rheumatoid factor (RF) antibodies in the blood stream. These are the first autoantibodies collected in the people affected with rheumatoid disease and its found in the lining of the joints.
            Antistreptolysin O: detects antibodies against streptolysin O , a substance produced by group A streptococuus bacteria.
            C-reactive protein: detects the CRP-a protein produced by the liver , as a result of  inflammation. Just like RF , CRP level may rise in presence of any autoimmune response or infection to bacteria.

            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '50.00'),
            array('id' => '10','name' => 'Immunoglobulins Blood Test','caption_text' => 'This test estimates the quantity of immunoglobulins also called as antibodies in the blood. This test usually measures IgG , IgM , and IgA.  If your levels of igG, igM, or IgA are too low or too high, it may be a sign of a serious health problem.
            Symptoms:
            Symptoms of levels that are too low include:
            Frequent and/or unusual bacterial or viral infections
            Chronic Diarrhoea
            Sinus infections
            Lung infections
            Family history of immunodeficiency
            ', 'description' => 'Diagnosis:
            An immunoglobulins blood test may be used to help diagnose a variety of conditions, including:
            Bacterial or viral infections
            Immunodeficiency, a condition that reduces the bodys ability to fight infections and other diseases
            An autoimmune disorder, such as rheumatoid arthritis or lupus. An autoimmune disorder causes your immune system to attack healthy cells, tissues, and/or organs by mistake.
            Certain types of cancer, such as multiple myeloma
            Infections in new-borns


            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '40.00'),
            array('id' => '11','name' => 'Hepatitis B Test','caption_text' => 'Medical information for Chlamydia Test', 'description' => 'Chlamydia PCR test, testing for the presence of Chlamydia Trachomatis.PCR (polymerase chain reaction) testing is a method to analyse a short sequence of DNA or RNA from samples containing only minute quantities of DNA or RNA.', 'status' => '1', 'price' => '40.00'),
            array('id' => '12','name' => 'Heart Disease Test','caption_text' => 'Heart Disease is any condition that affects your heart, as conornary heart disease, arrhythmia ets. According to the survey, heart disease is responsible for 1 in 4 four deaths in the United Kingdom each year. It’s a leading cause of death in both men and women
            Symptoms
            Common Symptoms include

            Irregular Heart Beat
            Chest pain
            Shortness of Breath
            Sweating
            Nausea

            ', 'description' => 'Are you at risk ?






            Smoking
            Hypertension
            High Cholesterol
            Diabetes
            Family History


            Diagnosis biomarker tested in our lab
            There is various test to diagnose heart disease. The doctor may start by asking
            Personal and Family medical history
            Current and past symptoms
            Laboratory test and an electrocardiogram.
            Lipid Profile
            The test measures the amount and type of lipids (fats) in the blood to determine the risk of developing cardiovascular disease (CVD). The examination entails
            Total Cholesterol: The test usually sums up the blood’s cholesterol content
            LDL (Low-density lipoprotein) Cholesterol: The LDL cholesterol is referred as bad cholesterol. Accumulation of LDL build up high risk of heart attack, stroke, and atherosclerosis.
            HDL (High-Density lipoprotein) Cholesterol: HDL is referred to as good cholesterol as it aids in the removal of LDL Cholesterol from the blood
            Triglycerides: In the blood, triglycerides are a form of fat. When you eat, your body transforms excess calories into triglycerides, which are then deposited in fat cells. Being overweight, eating too many sweets or drinking too much alcohol, smoking, being sedentary, or having diabetes with higher blood sugar levels are all linked to high triglyceride levels.
            Lipoprotein: The test is used to detect high levels of Lipoprotein (a), a kind of cholesterol carrier in the blood. The test assesses the risk of cardiovascular disease(CVD).
            C-reactive protein (CRP): As part of the body’s response to damage or infection , the liver produces C-reactive protein (CRP). The test detects inflammation caused by acute illnesses, monitors the degree of disease in chronic circumstances, and aids in the creation of a comprehensive picture of heart health by measuring the quantity of CRP in the blood.
            CK-MB: Creatine kinase-MB (CK-MB) is an enzyme that is mostly present in cardiac muscle cells. This test detects the presence of CK-MB in the blood. Only when the heart is injured will considerable levels of CK-MB be present.

            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '40.00'),
            array('id' => '13','name' => 'Venous Thromboembolism','caption_text' => 'Deep Vein thrombosis (DVT) are often underdiagnosed and serious medical condition which can be preventable. Deep vein thrombosisis a medical condition in which a blood clot develops in a vein deep within the body. Clots in the lower leg, thigh, or pelvis are most common, although they can also occur in the arm.
            Symptoms
            About half of people with DVT have no symptoms at all. The following are the most common symptoms of DVT that occur in the affected part of the body:
            Swelling
            Pain
            Tenderness
            Redness of the skin

            ', 'description' => '
            Are you at risk ?





            Age
            Injuryor Surgery
            Pregnancy
            Overweight or obese
            Genetic or family history

            Diagnosis biomarker tested in our lab
            D-Dimer test :
            D-Dimer is a type is protein commonly produced by blood clots. People with DVT have increased level of D-Dimer in the blood.

            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ', 'status' => '1', 'price' => '40.00'),
            array('id' => '14','name' => 'Diabetes Test','caption_text' => 'Diabetes is a metabolic disorder where blood sugar level is high. Its is mainly caused due to the failure of pancreas to produce the required amount of insulin f the cells of the body cannot absorb or respond to the insulin produced.
            There are maily two types of Diabetes
            Type 1 Diabetes - the pancreas fails to produce enough insulin. It is also referred as “insulin-dependent diabetes mellitus” (IDDM). This type generally occurs in childhood and is thus also known as “juvenile diabetes”.
            Type 2 Diabetes - the cells fail to respond to insulin. The most common cause is overweight and sedentary life. This form is referred as “non-insulin- dependent diabetes mellitus” (NIDDM) or “adult-onset diabetes”. Prediabetes
            Signs and Symptoms

            The warning signs and symptoms of diabetes include:






            Increased Thirst
            Dry Mouth
            Increased Hunger
            Weight loss
            Frequent Urination






            Fatigue
            Blurred Vision
            Headache
            Loss of Consciousness



            ', 'description' => 'Are you at risk?






            Family History
            Life Style
            Obesity
            Malfunction in pancreas
            Pregnancy




            Important information
            Sample type: Blood
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.


            Diagnosis
            HbA1c Blood test: Also called as glycated haemoglobin , doesn’t require fasting indicates average blood sugar level for past two or three months. It measures the percentage of blood sugar attached to haemoglobin, the oxygen-carrying protein in red blood cells.
            Albumin MST
            Glucose (HK)

            ', 'status' => '1', 'price' => '50.00'),
            array('id' => '15','name' => 'Gonorrhoea Test','caption_text' => 'Overview: Gonorrhoea is a sexually transmitted infection (STI) caused by the bacterium Neisseria gonorrhoeae that affects both males and females. Gonorrhoea is easily treated but can cause severe reproductive and health problems if left untreated. The test sample is collected by using a swab to get a sample of secretion or discharge from the infected area such as the cervix, urethra, penis, anus, or throat.
            Clinical Manifestations:
            Symptoms for Men:
            Pain or tenderness in the testicles.
            Swollen scrotum.
            Pain when urinating.
            White, yellow, or greenish discharge from the penis.
            Greater frequency or urgency of urination.
            Discoloration and swelling at the penis opening.
            Itching and soreness in your anus.
            Pain when having bowel movements.
            Symptoms for Women:
            Vaginal discharge.
            Pain during sex.
            Pain when urinating.
            Abdominal pain.
            An urge to urinate more frequently.
            Heavier periods or spotting between periods.
            Pain during penetrative vaginal sex.
            Sharp pain in your lower abdomen.
            Itching and soreness in your anus.
            Painful bowel movements
            ',
            'description' => 'Gonorrhoea can also affect these parts of the body:

            Rectum: Signs and symptoms include anal itching, pus-like discharge from the rectum, spots of bright red blood on toilet tissue and having to strain during bowel movements.
            Eyes: Gonorrhoea that affects your eyes can cause eye pain, sensitivity to light, and pus-like discharge from one or both eyes.
            Throat: Signs and symptoms of a throat infection might include a sore throat and swollen lymph nodes in the neck.
            Joints: If one or more joints become infected by bacteria (septic arthritis), the affected joints might be warm, red, swollen and extremely painful, especially during movement.

            Risk Factors:

            Age: a majority of cases of gonorrhea are seen at a young age.
            Sexual contact with multiple partners.
            Unprotected sex.
            Previous history of gonorrhea or other STDs.
            A sex partner who has concurrent partners.
            Have multiple sex partners.

            Complication:

            Untreated gonorrhoea can cause significant complications, such as:
            In males: inflammation of the prostate, Infertility, Increased risk of HIV/AIDS.
            In females: Pelvic Inflammatory Disease (PID), Infertility, Ectopic pregnancy, Increased risk of HIV/AIDS.
            Babies who contract gonorrhoea from their mothers during birth can develop blindness and sores on the scalp.


            Important information
            Sample type: Urine
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ',
            'status' => '1',
            'price' => '49.00'),
            array('id' => '16','name' => 'Chlamydia Test','caption_text' => 'Overview: Chlamydia is one of the most common sexually transmitted infections (STIs) in the UK. A chlamydia test detects the bacteria that cause chlamydia. Testing for chlamydia is done with a urine test or a swab test.
            Clinical Manifestations:
            A chlamydia infection doesn’t usually cause symptoms, so people may not know they have it. Untreated, chlamydia can cause serious health problems and infertility. If you do get symptoms, these usually appear between 1 and 3 weeks after having unprotected sex with an infected person. For some people they dont develop until many months later. Sometimes the symptoms can disappear after a few days. Even if the symptoms disappear you may still have the infection and be able to pass it on.
            Signs and symptoms of Chlamydia trachomatis infection can include:
            Painful urination
            Vaginal discharge in women
            Discharge from the penis in men
            Painful sexual intercourse in women
            Bleeding between periods and after sex in women
            Testicular pain in men
            ',
            'description' => 'Risk Factors:
            Age under 25 years.
            A new sexual partner.
            More than one sexual partner in the last year.
            Lack of consistent condom use.
            Infection is primarily through penetrative sex but can also occur via autoinoculation or splash from genital fluids.
            Complication:

            If chlamydia isnt treated, it can sometimes spread and cause potentially serious problems.
            In females: Pelvic inflammatory disease (PID), Difficulty getting pregnant or infertility, Persistent (chronic) pelvic pain, an increased risk of ectopic pregnancy.
            In males: Inflammation of the testicles, Reactive arthritis.


            Important information
            Sample type: Urine
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ',
            'status' => '1',
            'price' => '49.00'),
            array('id' => '17','name' => 'Herpes Test','caption_text' => 'Herpes is a mild condition that causes small sores to appear on the skin. People develop herpes after being exposed to the herpes simplex virus (HSV). This virus affects the external genitalia, anal region, mucosal surfaces, and skin in other parts of the body. Herpes is a long-term condition. However, many people never have symptoms even though they are carrying the virus.
            Clinical Manifestations:
            Most people infected with HSV dont know they have it because they dont have any signs or symptoms or because their signs and symptoms are so mild. When present, symptoms may begin about two to 12 days after exposure to the virus. If you experience symptoms of genital herpes, they may include:
            Pain or itching:  Experience pain and tenderness in your genital area until the infection clears.
            Small red bumps or tiny white blisters: These may appear a few days to a few weeks after infection.
            Ulcers: These may form when blisters rupture and ooze or bleed. Ulcers may make it painful to urinate.
            Scabs: Skin will crust over and form scabs as ulcers heal.
            Burning when you pee if your urine touches the herpes sores
            Having trouble peeing because the sores and swelling are blocking your urethra
            Pain around your genitals.

            If herpes is caused by HSV-2, you might also have flu-like symptoms, such as: swollen glands in your pelvic area, throat, and under your arms,fever,chills, headache, feeling achy and tired.
            ',
            'description' => 'Risk Factors
            Your risk of becoming infected with genital herpes may increase if you:

            Women are more likely to have genital herpes than are men. The virus is sexually transmitted more easily from men to women than it is from women to men.
            Have multiple sexual partners.





            Complications
            Complications associated with genital herpes may include:

            Other sexually transmitted infections: Having genital sores increases your risk of transmitting or contracting other sexually transmitted infections, including AIDS.
            Newborn infection: Babies born to infected mothers can be exposed to the virus during the birthing process. This may result in brain damage, blindness or death for the newborn.
            Bladder problems: In some cases, the sores associated with genital herpes can cause inflammation around the tube that delivers urine from your bladder to the outside world (urethra). The swelling can close the urethra for several days, requiring the insertion of a catheter to drain your bladder.
            Meningitis: In rare instances, HSV infection leads to inflammation of the membranes and cerebrospinal fluid surrounding your brain and spinal cord.
            Rectal inflammation (proctitis): Genital herpes can lead to inflammation of the lining of the rectum, particularly in men who have sex with men.


            Important information
            Sample type: Urine
            Kits will be posted to you containing instruction
            Take the test according to the instruction
            Post the kits back to us using our pre-paid envelope
            Your sample will be received by our laboratory team depending on the day and time of postage.
            If you purchase your test on Monday – Friday by 12.00 noon, you will receive your test kits the following day. However, any test purchased after 12.00 noon will be dispatched the day after we receive your order.
            Please note that any samples sent to us on Saturday will be received by our laboratory team on Monday.
            Our turnaround time is 2 working days upon receipt of your samples.
            If you drop your samples directly to our laboratory, your result will be ready within 22-48 hours upon receipt.
            ',
            'status' => '1',
            'price' => '49.00'),
            
        );
        foreach($products as $product){
            Product::insert($product);
        }
    }
}
